version: '3'

services:
  rasterframes-notebook:
    image: rasterframes-notebook
    ports:
      # jupyter notebook port
      - "8888:8888"
      # spark UI ports
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
      - "4043:4043"
      - "4044:4044"
# To save locally at './work' from the container:
    volumes:
      - ../../../src/main/notebooks:/home/jovyan/work